[package]
name = "staking"
version = "0.1.0"
edition = "2021"

[lib]
name = "staking"
crate-type = ["cdylib", "rlib"]

[dependencies]
anchor-lang = "^0.29.0"
serde = { version = "1.0", features = ["derive"] }
